# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 173b3e0ec07f08218f23e520f924586cfd07d170cfaac0652f3c403803844f63daeb565987ed66b342be34958657ffb6d4099dd4f62d7d2e155b7ac48c02710f

test:
  secret_key_base: 43fde1de3b2d6eff46f6667999ff1d5f85d7860ed529824fb7ae9491d64c8b510dd558ff7dfa004671251ca6f90508970b112f64a73f5d02b1b352dde43f3783

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
